const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

exports.createPDF = (data) => {
    return new Promise((res, rej) => {
        const doc = new PDFDocument({ 
            margin: 50,
            size: 'A4',
            info: {
                Title: 'GMB Audit Report',
                Author: 'PBM Intel',
                Subject: 'Google My Business Analysis'
            }
        });

        // Folder creation
        const outerPath = path.join(__dirname, "../public/reports");
        if (!fs.existsSync(outerPath)) fs.mkdirSync(outerPath, { recursive: true });

        // Fonts directory path
        const fontsPath = path.join(__dirname, "../assets/fonts");
        
        // Register custom fonts if they exist, otherwise use fallback
        let headingFont = "Helvetica-Bold";
        let textFont = "Helvetica";
        
        try {
            const akiraPath = path.join(fontsPath, "AkiraExpanded.otf");
            const jonesPath = path.join(fontsPath, "Jones.otf");
            
            if (fs.existsSync(akiraPath)) {
                doc.registerFont("AkiraExpanded", akiraPath);
                headingFont = "AkiraExpanded";
            }
            if (fs.existsSync(jonesPath)) {
                doc.registerFont("Jones", jonesPath);
                textFont = "Jones";
            }
        } catch (err) {
            console.log("Custom fonts not found, using fallback fonts");
        }

        // File name sanitizer
        const sanitize = (name) => {
            if (!name || name === "Business Name Not Found") return `GMB_Report_${Date.now()}`;
            return name.replace(/[<>:"/\\|?*]/g, "_").trim();
        };

        const fileName = `${sanitize(data.bisName)}.pdf`;
        const filePath = path.join(outerPath, fileName);

        const stream = fs.createWriteStream(filePath);
        doc.pipe(stream);

        // ---------------------------------------------------
        // HEADER DESIGN - Professional & Clean
        // ---------------------------------------------------
        const headerY = 50;
        
        // Main Title with Akira Expanded (Red) - Centered
        doc
            .font(headingFont)
            .fontSize(28)
            .fillColor("#cf1020") 
            .text("GMB", { align: "center", characterSpacing: 2 });
        
        doc
            .font(headingFont)
            .fontSize(32)
            .fillColor("#cf1020")
            .text("AUDIT REPORT", { align: "center", characterSpacing: 2 });

        doc.moveDown(0.3);

        // Subtitle
        doc
            .font(textFont)
            .fontSize(10)
            .fillColor("#666666")
            .text("Generated by PBM Intel | Automated GMB Analyzer", { align: "center" });

        // Date
        const currentDate = new Date().toLocaleDateString('en-US', { 
            year: 'numeric', 
            month: 'long', 
            day: 'numeric' 
        });
        doc
            .font(textFont)
            .fontSize(9)
            .fillColor("#999999")
            .text(`Report Date: ${currentDate}`, { align: "center" });

        // Elegant divider
        const dividerY = headerY + 115;
        doc
            .moveTo(50, dividerY)
            .lineTo(545, dividerY)
            .strokeColor("#cf1020")
            .lineWidth(2)
            .stroke();

        doc.y = dividerY + 30;

        // ---------------------------------------------------
        // SECTION BOX GENERATOR - Professional Design
        // ---------------------------------------------------
        const section = (title, value, impactText, isMissing = false) => {
            const textWidth = 460;
        
            // Calculate heights
            const valueHeight = doc.heightOfString(value || "Missing", {
                width: textWidth,
                lineGap: 2
            });
        
            // Impact height only if value is missing
            const impactHeight = isMissing
                ? doc.heightOfString(impactText, { width: textWidth, lineGap: 2 })
                : 0;
        
            const titleHeight = 20;
            const padding = 40;
        
            // Dynamic height based on content
            const estimatedHeight = titleHeight + valueHeight + impactHeight + padding;
        
            // Page break BEFORE drawing
            if (doc.y + estimatedHeight > doc.page.height - 60) {
                doc.addPage();
            }
        
            const startY = doc.y;
            const borderRadius = 6;
        
            // Background box
            doc
                .roundedRect(50, startY, 495, estimatedHeight, borderRadius)
                .fillAndStroke("#FFFFFF", "#E8E8E8");
        
            // Accent bar
            doc
                .rect(50, startY, 4, estimatedHeight)
                .fill(isMissing ? "#cf1020" : "#F0F0F0");
        
            // Title
            doc
                .font(headingFont)
                .fontSize(16)
                .fillColor("#cf1020")
                .text(title.toUpperCase(), 70, startY + 12, {
                    width: textWidth,
                    characterSpacing: 1
                });
        
            // VALUE
            const valueY = startY + 12 + titleHeight;
        
            doc
                .font(textFont)
                .fontSize(13)
                .fillColor(isMissing ? "#cf1020" : "#1A1A1A")
                .text(value || "Missing", 70, valueY, {
                    width: textWidth,
                    lineGap: 2
                });
        
            // IMPACT TEXT ONLY IF MISSING
            if (isMissing) {
                const impactY = valueY + valueHeight + 10;
        
                doc
                    .font(textFont)
                    .fontSize(9)
                    .fillColor("#666")
                    .text(impactText, 70, impactY, {
                        width: textWidth,
                        lineGap: 1
                    });
            }
        
            // Move cursor for next box
            doc.y = startY + estimatedHeight + 18;
        };
        
        
        // ---------------------------------------------------
        // SECTIONS - Professional Layout
        // ---------------------------------------------------

        // Helper function to check if value is missing
        const isMissingValue = (value, notFoundText = null) => {
            if (!value) return true;
            if (notFoundText && value === notFoundText) return true;
            if (value === "Missing" || value === "Not Found") return true;
            return false;
        };

        // Business Name
        const bisName = data.bisName || "Missing";
        section(
            "Business Name",
            bisName,
            "A correct business name improves visibility and brand trust.",
            isMissingValue(bisName, "Business Name Not Found")
        );

        // Category
        const category = data.category || "Category Not Found";
        section(
            "Category",
            category,
            "Primary category strongly impacts search ranking relevance.",
            isMissingValue(category, "Category Not Found")
        );

        // Rating
        const rating = data.rating || "Rating Not Found";
        section(
            "Rating",
            rating,
            "High ratings boost ranking & increase customer trust.",
            isMissingValue(rating, "Rating Not Found")
        );

        // Total Reviews
        const totalReviews = data.totalReviews || "Not Found";
        section(
            "Total Reviews",
            totalReviews,
            "More reviews = stronger trust + higher Google ranking.",
            isMissingValue(totalReviews, "Not Found")
        );

        // Replies Count
        const replyRate =
            data.repliesCount && data.totalReviews && !isMissingValue(data.totalReviews)
                ? ((data.repliesCount / parseInt(data.totalReviews.replace(/[^\d]/g, "")) || 1) * 100).toFixed(1)
                : "0";
        const repliesText = `${data.repliesCount || 0} replies${replyRate !== "0" ? ` (${replyRate}% reply rate)` : ""}`;
        section(
            "Owner Replies",
            repliesText,
            "Responding to reviews boosts engagement & ranking.",
            false
        );

        // Address
        const address = data.address || "Address Not Found";
        section(
            "Address",
            address,
            "Accurate address helps with map positioning and 'near me' searches.",
            isMissingValue(address, "Address Not Found")
        );

        // Website
        const website = data.website || "Website Not Found";
        section(
            "Website",
            website,
            "Website link improves authority & CTR from GMB.",
            isMissingValue(website, "Website Not Found")
        );

        // Phone
        const phone = data.phone || "Phone Not Found";
        section(
            "Phone Number",
            phone,
            "Consistent phone number improves NAP score.",
            isMissingValue(phone, "Phone Not Found")
        );

        // Establishment Date
        const date = data.date || "Date Not Found";
        section(
            "Establishment Date",
            date,
            "Older businesses may have stronger trust signals.",
            isMissingValue(date, "Date Not Found")
        );

        // Description
        const description = data.description ? (data.description.length > 200 ? data.description.substring(0, 200) + "..." : data.description) : "No description available";
        section(
            "Business Description",
            description,
            "Keyword-rich descriptions improve relevance.",
            !data.description || data.description === "No description available"
        );

        // Products
        const productsText = data.products && data.products.productCount > 0
            ? data.products.products.join(", ")
            : "No products/services listed";
        section(
            "Products / Services",
            productsText,
            "Providing product/service lists helps Google match customer searches.",
            !data.products || data.products.productCount === 0
        );

        // Updates
        const updatesCount = data.totalUpdates || 0;
        section(
            "Total Updates (Posts)",
            `${updatesCount} updates`,
            "Posting frequently signals active business operations.",
            false
        );

        // ---------------------------------------------------
        // FOOTER - Professional Design
        // ---------------------------------------------------
        doc.moveDown(2);
        
        // Footer divider
        const footerY = doc.y;
        doc
            .moveTo(50, footerY)
            .lineTo(545, footerY)
            .strokeColor("#E8E8E8")
            .lineWidth(1)
            .stroke();

        doc.moveDown(1);
        
        // Footer text
        doc
            .font(textFont)
            .fontSize(9)
            .fillColor("#999999")
            .text("Report generated automatically using PBM Intel GMB Analyzer", { align: "center" });
        
        doc
            .font(textFont)
            .fontSize(8)
            .fillColor("#CCCCCC")
            .text("© PBM Intel - All rights reserved", { align: "center" });

        doc.end();

        stream.on("finish", () => res(filePath));
        stream.on("error", (err) => rej(err));
    });
};
